#!/bin/bash
if [[ -z $HMHOME || $HMHOME = "" ]];then
	HMHOME=`pwd`; 
	echo "install hmtools .. ">&2
	cmd="
	## added by hmtools
	HMHOME=$HMHOME; export HMHOME;
	PATH=\$PATH:\$HMHOME:\$HMHOME/bin; export PATH;
	## end hmtools"
	echo "$cmd" >> ~/.bash_profile
fi


. $HMHOME/src/polya.sh
usage="
hm <commands>:
	<commands>:
	 batch_polya : one click batch program
	 filter .. : calculate polyA score
"
if [[ $# -lt 1 ||  -z $1 ]];then
	echo "$usage"; 
else
	eval $1 ${@:2}
fi

